### ISSUE TITLE
Enigma sleep? 

### ISSUE THREAD

**Issue by sofievalk** [MICA-MNI/ENIGMA#1]
Hi Sara and Boris,

very cool toolbox and excellent use of emoticons! I was just browsing around. Let me know if you are also interested in Enigma sleep. I am sort of involved there and possibly sleep has also a lot of relationships with the other working group disorders. 

cheers,
Sofie

**Comment by saratheriver** [comment]
Hi Sophie!

Thanks for your compliment! We're in the process of collecting as much data as we can so we're obviously very interesting in adding ENIGMA Sleep data!
