### ISSUE TITLE
More surface to plot visualization

### ISSUE THREAD

**Issue by gourdchen** [MICA-MNI/ENIGMA#10]
The visualiztion of surface in enigma toolbox is so beautiful and convenient.
However, the surfaces in it are just two: the pial of fsa and conte69. How could I do if I want to add a inflated surface to plot？

**Comment by saratheriver** [comment]
Hello!

Thank you! We're working on making the function a bit more flexible. But for now you could add your inflated surfaces in the same folder as the other surfaces and add an extra "if" statement in the plot_cortical script where it loads the surfaces.

Does this make sense?

Sara.

**Comment by gourdchen** [comment]
Thanks for your reply!! 
I found there are two files that seem like same: "** lh.surf.gii"  and "**lh.gii". 
I just add the **lh.gii file and it works. Am I right? Are there any other documents required such as "lh.sulc"?

**Comment by saratheriver** [comment]
No you only need to add the lh.surf.gii and rh.surf.gii files!
