### ISSUE TITLE
Parcellation 

### ISSUE THREAD

**Issue by MarcKhoury8** [MICA-MNI/ENIGMA#11]
Hi, 

Currently trying to complete the Vertexwise → parcellated data

I just want to confirm that the ENIGMA toolbox can indeed take freesurfer table outputs from aparc_stats? I've obtained thickness values for lh (34) and rh (34) into txt formats. Not sure if ENIGMA is able to map these values onto atlas? 

Getting this error: 

>> CT_schaefer_200 = surface_to_parcel(CT, 'aparc_fsa5')
The logical indices in position 2 contain a true value outside of the array bounds.

Error in surface_to_parcel (line 31)
    surf2parcel(:, ii)  = nanmean(surf_data(:, label_vector == thisparcel), 2);

CT looks like the following : 
CT =

  Columns 1 through 15
    2.5700    2.3310    2.2130    1.9630    3.2860    2.7520    2.2920    2.7030    2.0360    2.1370    2.3080    2.0430    2.2780    2.6820    2.6050
  Columns 16 through 30
    2.2320    2.4320    2.3020    2.2680    1.7770    2.0400    2.1910    2.3720    2.2140    2.3880    2.1750    2.2760    2.1000    2.7060    2.3550
  Columns 31 through 45
    2.2690    3.4880    2.3270    2.6600    2.4280    2.4940    2.2360    2.2080    3.6770    2.7530    2.2590    2.6610    2.0990    2.2480    2.4490
  Columns 46 through 60
    2.1280    2.3300    2.6960    2.7750    2.2880    2.4240    2.5230    2.2940    1.8560    2.1740    2.2920    2.3980    2.1880    2.5320    2.2450
  Columns 61 through 68\
    2.3160    2.1050    2.7430    2.4480    2.3960    3.5600    2.5450    2.5090

**Comment by saratheriver** [comment]
Hi !

Thanks for using the Toolbox! I'm a bit confused as what you are trying to do here. If you want to convert your FreeSurfer CT (68 regions) to vertexwise fsaverage5, then you should use the following parcel_to_surface function (*and not the `surface_to_parcel` one):

`ct_fsa5 = parcel_to_surface(ct, 'aparc_fsa5');`

Does that make more sense?

Sara.

**Comment by MarcKhoury8** [comment]
Hi Sara, 

Thank you for the reply. This was very helpful. 

What would you say is the most optimal toolbox for Freesurfer data in general? Usually my processed data is formatted as Patient row by 68 regions (in csv format) for the aparc.stats outputs, however most cortical mapping softwares require cifity, nifti, gifti formats to upload data. And so, unless I reprocessed the data into these formats, I cant use them.
That said, I came across the MICA toolbox's and am fascinated, would love to learn all. Are all MICA toolbox's csv/txt compatible? Thanks Sarah, would love to know more about this.

**Comment by MarcKhoury8** [comment]
Example Dataset "https://user-images.githubusercontent.com/101748806/167482091-b5e4b8a9-131a-4826-bc04-99dbdba146aa.png"

**Comment by saratheriver** [comment]
Hi!

There are multiple toolboxes available out there but if you want we provide tutorials on how to load data in [.csv format](https://enigma-toolbox.readthedocs.io/en/latest/pages/16.import/index.html#txt-csv) and how to export it in a different format [eg gifti](https://enigma-toolbox.readthedocs.io/en/latest/pages/18.export/index.html#gifti-gii).

Hope this helps,

Sara.
