### ISSUE TITLE
ImportError: cannot import name 'VTK_UNICODE_STRING' from 'vtk.util.vtkConstants' when importing load_summary_stats

### ISSUE THREAD

**Issue by WMDA** [MICA-MNI/ENIGMA#15]
Hi 

I am getting this import error ImportError: cannot import name 'VTK_UNICODE_STRING' from 'vtk.util.vtkConstants' when I try to ```import from enigmatoolbox.datasets import load_summary_stats```  

This happens in python 3.8 and python 3.9 on a linux ubuntu and linux redhat distros

It looks like VTK_UNICODE_STRING is depreciated (https://gitlab.kitware.com/vtk/vtk/-/issues/18327) and there is definitely no  VTK_UNICODE_STRING in vtk.util.vtkConstants.

I can do everything I want to do by ``` from vtk.util.vtkConstants import VTK_STRING#, VTK_UNICODE_STRING``` in the vtk.wrappers.utils file and was going to issue a pull request however saw this then effects the is_vtk_string() function in that file which seems to be used all over vtk.interface and my pull request would probably break everything.

Thanks

**Comment by joebathelt** [comment]
I managed to get around that error by downgrading vtk to version 9.1.0:
```
pip install --upgrade vtk==9.1.0
```

**Comment by saratheriver** [comment]
Noice - thank you beautiful people 😇 The toolbox was only tested on python 3.7 so I appreciate you pointing out these bugs + fixes!
