### ISSUE TITLE
bug report about the version 1.1.3

### ISSUE THREAD

**Issue by gourdchen** [MICA-MNI/ENIGMA#17]
In vtk_interface/pipeline.py 
About line 61:
when add_conn is False, the isinstance(add_conn,int) will return True, because it can't discriminate "bool" and "int".
And I don't if there is any other problems such as above.

In 1.1.1 ,there is     if add_conn is True or type(add_conn) == int , it works!

**Comment by saratheriver** [comment]
Thanks so much for pointing this out! I changed it back 😀
