### ISSUE TITLE
A question about vector images for plot_cortical function

### ISSUE THREAD

**Issue by wwwhales** [MICA-MNI/ENIGMA#20]
Hi, 

thank you so much for creating an incredible brain visualization tool that allows us to see very clearly the connections between molecules or genes and each brain region. 

However, when I use the plot_cortical function in python, I found a problem, that is how can I use the plot_cortical or plot_subcortical functions to generate cortical and subcortical images that are exported as editable vectors or 3D images? I would appreciate it if you could answer my question.

**Comment by saratheriver** [comment]
Unfortunately, that is not an option at the moment.
