### ISSUE TITLE
Obtaining Cohen's D for cortical thickness

### ISSUE THREAD

**Issue by cestevezfraga** [MICA-MNI/ENIGMA#22]
Hi Enigma team, 

I am trying to apply to my data a pipeline that had been previously used to analyse results from the Enigma dataset. There, the authors used already processed data from Enigma using the parcellated cortical thickness data across 68 regions from the DK atlas. They used the cortical thickness of patients vs controls) 

In my dataset, I have obtained the ROI-specific cortical thickness data for each subject, and I have the demographics too. Now I would like to obtain Cohen's d for the patients vs controls also adjusting for covariates (age/sex/site etc...). I have been able to obtain from enigma Cohen's D in Enigma, but I have been unable to find out how these were obtained, and particularly how could I get these after adjusting for confounders. 

Would it be possible to share these methods?

Many thanks,

Best regards, 

Carlos

**Comment by saratheriver** [comment]
Hi Carlos,

The meta-analytical pipelines can be found on the ENIGMA website (https://enigma.ini.usc.edu). They are usually derived from R.

Hope this helps,

Sara.

From: Carlos Estevez-Fraga ***@***.***>
Date: Thursday, January 19, 2023 at 8:12 AM
To: MICA-MNI/ENIGMA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MICA-MNI/ENIGMA] Obtaining Cohen's D for cortical thickness (Issue #22)

Hi Enigma team,

I am trying to apply to my data a pipeline that had been previously used to analyse results from the Enigma dataset. There, the authors used already processed data from Enigma using the parcellated cortical thickness data across 68 regions from the DK atlas. They used the cortical thickness of patients vs controls)

In my dataset, I have obtained the ROI-specific cortical thickness data for each subject, and I have the demographics too. Now I would like to obtain Cohen's d for the patients vs controls also adjusting for covariates (age/sex/site etc...). I have been able to obtain from enigma Cohen's D in Enigma, but I have been unable to find out how these were obtained, and particularly how could I get these after adjusting for confounders.

Would it be possible to share these methods?

Many thanks,

Best regards,

Carlos

**Comment by cestevezfraga** [comment]
Hi Sara, 

Sorry to reach out again. In https://enigma.ini.usc.edu/ I am able to find the protocols and code to perform QC or to obtain cortical thickness etc... I am also able to find the already calculated Cohen's D for each disorder. However, I am unable to find the pipelines to estimated Cohen's D from cortical thickness data in the ENIGMA website. 

Looking at methods in the different papers it seems that the statistical models were different between the analysis so I guess it is disease-specific.

Would you be able to show me where are 1-2 examples so I could take it from there?

Many thanks again,

Best regards, 

Carlos

**Comment by saratheriver** [comment]
E.g. for ENIGMA-Epilepsy: https://enigma.ini.usc.edu/ongoing/enigma-epilepsy/enigma-epilepsy-protocols/

From: Carlos Estevez-Fraga ***@***.***>
Date: Friday, January 20, 2023 at 9:22 AM
To: MICA-MNI/ENIGMA ***@***.***>
Cc: saratheriver ***@***.***>, Comment ***@***.***>
Subject: Re: [MICA-MNI/ENIGMA] Obtaining Cohen's D for cortical thickness (Issue #22)

Hi Sara,

Sorry to reach out again. In https://enigma.ini.usc.edu/ I am able to find the protocols and code to perform QC or to obtain cortical thickness etc... I am also able to find the already calculated Cohen's D for each disorder. However, I am unable to find the pipelines to estimated Cohen's D from cortical thickness data in the ENIGMA website.

Looking at methods in the different papers it seems that the statistical models were different between the analysis so I guess it is disease-specific.

Would you be able to show me where are 1-2 examples so I could take it from there?

Many thanks again,

Best regards,

Carlos

**Comment by saratheriver** [comment]
It also generates a SummaryStats*.txt file which should have Cohen’s d values.

From: Carlos Estevez-Fraga ***@***.***>
Date: Friday, January 20, 2023 at 12:16 PM
To: MICA-MNI/ENIGMA ***@***.***>
Cc: saratheriver ***@***.***>, Comment ***@***.***>
Subject: Re: [MICA-MNI/ENIGMA] Obtaining Cohen's D for cortical thickness (Issue #22)

Sorry Sara but I do not find the pipeline to obtain the Cohen's d there.

In the 'protocols' section of the 'epilepsy' group there are documents to get the raw cortical thickness and QC it, but not about how to obtain Cohen's d which is what I am interested in.

The R script that is within "Step 4: Get population summary statistics of the cortical traits and related histograms" (https://enigma.ini.usc.edu/wp-content/uploads/CORTEX/ENIGMA_CortexROI_plots.R) is just to plot the data.

Isn't there a specific pipeline to estimate Cohen's d? Apologies if I am missing it.

**Comment by cestevezfraga** [comment]
Hi Sara, 

I have managed to obtain Cohen's d for my cortical thickness data using the T value that I obtained from the linear mixed models (lm(ROI_thickness ~ Dx + age1 + sex + site, data = ct_data)

I have another question though.  I see in https://enigma-toolbox.readthedocs.io/en/latest/pages/03.loadct/index.html that the cortical thickness values were Z-scored. Were they Z-scored before Cohen's d was obtained? In that case that would not make any difference in the T values or Cohen's d so I do not see the point unless it was for visual representation...I also wondered whether actually, it was cohen's d values being Z scored between the different ROIs but that was actually not the case as the mean of the D values is not zero. Do you know where was this step introduced? 

Many thanks

Best regards, 

Carlos
