### ISSUE TITLE
The interpolation method of surface mapping [how to change to nearest method]

### ISSUE THREAD

**Issue by gourdchen** [MICA-MNI/ENIGMA#23]
When I draw a atlas in enigmatoolbox, the color of  parcellations' edge will be strange, as follows:
 
![image](https://user-images.githubusercontent.com/35017063/218477705-bf4fcd21-59be-4608-a4f3-3058db0076c1.png)

I guess it is due to the interpolation before the image rendering, but I can't find how to change the method in the code. I am not familar with the VTK, it seems a difficult task for me. So, would you please help me to solve this problem? Thank you!

**Comment by saratheriver** [comment]
You can convert your array to integer before
`array_name=my_array.astype(int)`

**Comment by gourdchen** [comment]
Thanks for your kindly help!
