### ISSUE TITLE
surface_to_parcel ROI labels

### ISSUE THREAD

**Issue by araikes** [MICA-MNI/ENIGMA#25]
Hi @saratheriver 

Can you clarify something for me? I was using my own data and following the examples for `surface_to_parcel` using `aparc_fsa5`. The output I get from that has 71 values whereas I would expect 68 parcels. Likewise `schaefer_100_fsa5` has 101, rather than 100. 

I assume the first value to be unparcellated areas (label = 0), but for `aparc_fsa5`, what are the extra 2 values and are they on the front end or back end of the data? Would it be possible for `surface_to_parcel` to have the ROI label names for export to CSV?

**Comment by saratheriver** [comment]
Hello @araikes,

The aparc parcellation has 71 values - in ENIGMA they remove the midline mask and both corpus callosum. 

If you do:
`from enigmatoolbox.utils import parcel_to_surface, surface_to_parcel
a = parcel_to_surface(np.ones(68,), 'aparc_fsa5')
b = surface_to_parcel(a, 'aparc_fsa5')`

You can see where the extra values are being added. And if plot them on the surface you'll see where they are on the brain as they will have a value of 0.

As for the labels, the only function that we have currently is as follows:

`from enigmatoolbox.datasets import load_fc
_, labels, _, _ = load_fc(parcellation='aparc')`

Please note however these labels do not include the midline mask nor the CC (for aparc).

Hope this helps,

Sara.
