### ISSUE TITLE
About the Connectivity Data in the ENIGMA Toolbox

### ISSUE THREAD

**Issue by WY-SHI** [MICA-MNI/ENIGMA#28]
Hi @saratheriver,

Recently, I used the functional and structural connectivity data provided by the useful toolbox for exploring the relationship between brain function and structure, also the effect caused by using different parcellations. However, the `Glasser_360` and `Schaefer` templates are both partitioned to some extent based on functional information. I trying to introduce 'Brainneome Atlas', which is generated using structural information for further comparison. 

So, I wonder if you can add the _functional and structural connectivity data_ generated with `Brainnetome Atlas` into ENIGMA Toolbox, or provide the _detailed parameters_ and _subject list_ of HCP used for generating the connectivity data, especially regarding the DTI data processing? If there is a publicly available code, it would be even better.

Thanks a lot!

**Comment by saratheriver** [comment]
Hello,

The data was processed using micapipe, an open-source and fully automated processing pipeline for multimodal MRI data (https://micapipe.readthedocs.io/en/latest/). 

The subject list we used is here 
[hcp_subject_list.txt](https://github.com/MICA-MNI/ENIGMA/files/12294191/hcp_subject_list.txt)

Hope this helps!
