### ISSUE TITLE
Matching data to expected label order for plotting

### ISSUE THREAD

**Issue by pauldhami** [MICA-MNI/ENIGMA#36]
Greetings,

I have some external data I would like to plot onto the surface with the ENIGMA toolbox. I have the data and know which value corresponds to what region with respect to the DK atlas (68 regions). However, I do not know what order the plotting function expects for the values (i.e., which index corresponds to what label). Where can I find the set of atlas labels that ENIGMA expects the data to match in order?

Thank you.

**Comment by saratheriver** [comment]
Hello,

You can find it [here](https://github.com/MICA-MNI/ENIGMA/blob/master/enigmatoolbox/datasets/matrices/hcp_connectivity/funcLabels_ctx.csv).

Sara.
