### ISSUE TITLE
Unable to coerce Matrix: zscore_matrix

### ISSUE THREAD

**Issue by ConorOW** [MICA-MNI/ENIGMA#5]
Hi ENIGMA-TOOLBOX team,
Thanks for doing such a great job putting this together.

This isn't really a support issue as much as a cry for help...

I'm trying to use the toolbox to load some of my own cortical and subcortical data, z-score it and display it. I'm following the same format as the example data with the following parameters:

`
print(cov.shape)
print(metr1_SubVol_r.shape)
print(metr2_CortThick.shape)
print(metr3_CortSurf.shape)
(159, 10)  
(159, 18)  
(159, 74)  
(159, 74)  `

I can reverse and re-order the subcortical volumes file, then use the `SV_z = zscore_matrix(metr1_SubVol_r.iloc[:, 1:-1], group, controlCode)`. When I try and make a zscore matrix for my two CortThick and CortSurf `CT_z = zscore_matrix(metr2_CortThick.iloc[:, 1:-1], group, controlCode)` and `CT_z = zscore_matrix(metr2_CortThick.iloc[:, 1:-1], group, controlCode)`

I get an error with my dataframe:

`raise ValueError(
 "Unable to coerce to DataFrame, shape "
 f"must be {left.shape}: given {right.shape}"
ValueError: Unable to coerce to DataFrame, shape must be (159, 72): given (159, 70)`

Can anyone see what I am doing wrong here? Could it be something is amiss with the csv I am uploading?

Super grateful for any pointers.

Conor

**Comment by saratheriver** [comment]
Hi Conor, what's cracking?

Thanks for using the Toolbox !

It's a bit hard to find what's going wrong here because I can't reproduce the error, but here's a few things you can try:

1 - Load your csv as follows:
```
import pandas as pd
pd.read_csv('/path/to/your/csv.csv', error_bad_lines=False)
```

2 - If your _**cortical**_ files have the same shape and column order as our example data (which I assume they do), then be sure to exclude the last 6 columns (remove only the last one as you did for the subcortical data) from the z-score calculations:
```
from enigmatoolbox.utils.useful import zscore_matrix
group = cov['Dx'].to_list()
controlCode = 0
CT_z = zscore_matrix(metr2_CortThick.iloc[:, 1:-5], group, controlCode)
SA_z = zscore_matrix(metr3_CortSurf.iloc[:, 1:-5], group, controlCode)
```

Let us know whether this fixes it, otherwise we'll try something else!

Have a great Wednesday 🤠

Sara.

**Comment by ConorOW** [comment]
Thanks so much Sara, that is a big help. I think my issue is with my messy dataset, so I am going to trim it right back so its nice and clean, see if I can get it going with those commands, then I will work my way back from there. Really excited to use the toolbox!! Will report back shortly

**Comment by ConorOW** [comment]
Sara, it looks to be working really well now. I went back over your instructions, step-by-step, and managed to get it working. I think I was setting the end of the data frame incorrectly. Anyway thanks again for the support, and for doing such a cool toolbox! Cheers, Conor
