### ISSUE TITLE
Addition of DK-114 parcellation

### ISSUE THREAD

**Issue by gabocas** [MICA-MNI/ENIGMA#6]
Dear enigma toolbox team,

First of all, congratulations on such a cool and useful toolbox. Taking advantage of your kind offer about adding new parcellations to the toolbox, would it be possible to add the Desikan-Killiany atlas 114 ROIs (DK-114) parcellation to the enigma toolbox? (commonly used by van den Heuvel group publications, e.g. https://doi.org/10.1093/brain/awz330)

Best,

Gabriel

**Comment by saratheriver** [comment]
Hi Gabriel!

Thanks for using the toolbox. We can indeed add that parcellation but it may take a little while (especially for HCP connectivity matrices).

Did you need it for one function in particular or most of them? 

All the best,

Sara.

**Comment by gabocas** [comment]
Hi Sara,
thanks for your answer. I would just need it for converting data between parcellations, meaning only the parcel_to_surface function, particularly from the DK-114 parcellation to the conte69 surface.

Best,

Gabriel

**Comment by saratheriver** [comment]
Hi Gabriel,

I can't seem to find the mapping between DK-114 and conte69 or fsaverage. If you can obtain this then I could implement it in the toolbox. 

Sorry I can't be of any more help,

Sara.
