### ISSUE TITLE
adding titles for various plotting features

### ISSUE THREAD

**Issue by llevitis** [MICA-MNI/ENIGMA#7]
Hi @saratheriver and team! Thank you for making this toolbox - the functionality and scope of it are really impressive. I have a probably very dumb question but have not been able to figure it out on my own. I have been playing around with some of the plotting functions, e.g. `plot_cortical`, and I cannot seem to figure out if it is possible to add a title to the plots. The documentation and examples show plots with a beautiful standardized font and titles, but the corresponding code blocks do not seem to include the addition of titles. I looked into the plotter functionality underlying `plot_cortical` and related functions, and I am wondering if I have to pass a title to *kwargs, and if so, how to do that. I would appreciate any guidance here :)

**Comment by saratheriver** [comment]
Hi Liza!

Thanks for using the Toolbox!

Yeah I cheated a bit and included the title and colorbar numbers manually afterward with my favorite font 😂

In python, you can do `plot_cortical(..., label_text={'top': 'MyTitle'})`.

In matlab, you could add `title('MyTitle'); axis off;` to line 62 of plot_cortical, however, it will not be entirely centered and that's one of the reasons we haven't included it as a name-value argument.

Hope this helps!

Sara.
